# Add configuration values here, as shown below.
#
# pusher_app_id: "2954"
# pusher_key: 7381a978f7dd7f9a1117
# pusher_secret: abdc3b896a0ffb85d373
# stripe_api_key: sk_test_2J0l093xOyW72XUYJHE4Dv2r
# stripe_publishable_key: pk_test_ro9jV5SNwGb1yYlQfzG17LHK
#

spotify_key: 56cc90fd3b7d438f88f5efc299aada0b

spotify_secret: d22fba2017a04f00ac6ac14043094582

secret: uxZRYJoq@keDuOYjn!WOQ8253wzvX&BbpgplNAE!JMP@GFhzximvEIraysN&8Xns%yoFI1CTioWa!Xg9l3N2sanUu@3a!IztxUw

# production:
#   stripe_api_key: sk_live_EeHnL644i6zo4Iyq4v1KdV9H
#   stripe_publishable_key: pk_live_9lcthxpSIHbGwmdO941O1XVU
